### ISSUE TITLE
Calculator crashing SSP

### ISSUE THREAD

**Issue by meradudd** [DoughnutDev/DonutCraftATL#1]
I have noticed several CTDs associated with Calculator.

Crashed when trying to use the Atomic Calculator
[crash-2016-07-17_10.50.36-client.txt](https://github.com/DoughnutDev/DonutCraftATL/files/369067/crash-2016-07-17_10.50.36-client.txt)

Crashed when using small stone
[crash-2016-07-17_12.23.50-client.txt](https://github.com/DoughnutDev/DonutCraftATL/files/369070/crash-2016-07-17_12.23.50-client.txt)

Crashed when using soil
[crash-2016-07-17_12.49.19-client.txt](https://github.com/DoughnutDev/DonutCraftATL/files/369060/crash-2016-07-17_12.49.19-client.txt)

Thank you for your assistance.

**Comment by DoughnutDev** [comment]
Should be fixed in 0.0.5b
